Fix string concatenation
- Some of the status_messages weren't displayed because of syntax error in
  handle_threads() function in FetchGetCommand class.

Fixes this error message:

    Traceback (most recent call last):
      File ".\Fetch.py", line 176, in <lambda>
        File ".\Fetch.py", line 182, in handle_threads
        TypeError: not all arguments converted during string formatting